config = {
    'BW_DIR': '/nird/projects/NS9001K/sso102/Python/TOOLS/S2S-download/data/BW',
    'CF_DATA_DIR': '',
    'S2S_DIR': '/nird/projects/NS9853K/DATA/S2S',
     'S2SEUR_DIR': '',
    'SFE_DIR': '',
    'ERA5_daily_DIR': '',
    'ERA5_monthly_DIR': '',
    'S2S_DIR_summer2018': '',
    #'SAVEFIG': '/nird/projects/NS9001K/sso102/Python/S2S-download/figures/',
    'SAVEFIG': '/nird/projects/NS9001K/sso102/Python/S2S-download/figures_summer2018/',
   # 'VALID_DB': '/nird/projects/NS9001K/sso102/Python/S2S-download/data/valid_db/',
    'VALID_DB': '/nird/projects/NS9001K/sso102/Python/S2S-download/data/valid_db_summer2018/',
    #'S2SF': '/nird/projects/NS9853K/DATA/S2S/forecast/ECMWF/sfc/',
    #'S2SH': '/nird/projects/NS9853K/DATA/S2S/hindcast/ECMWF/sfc/',
    'S2SF': '/nird/projects/NS9853K/DATA/S2S/SUMMER2018/forecast/ECMWF/sfc/',
    'S2SH': '/nird/projects/NS9853K/DATA/S2S/SUMMER2018/hindcast/ECMWF/sfc/',
    'ERA5': '/nird/projects/NS9853K/DATA/SFE/ERA_daily_nc/grid_15/',
    'SITES': '/nird/projects/NS9001K/sso102/Python/S2S-download/data/BW/sites.json',
    'DOMAINS': '/nird/projects/NS9001K/sso102/Python/S2S-download/data/EIDE/domains.json',
    'BW': '/nird/projects/NS9001K/sso102/Python/S2S-download/data/BW/BW_temperature/',
    'IMR': '/nird/projects/NS9001K/sso102/Python/S2S-download/data/nird_copy/IMR/fastestasjoner/',
    'EIDE': '/nird/projects/NS9001K/sso102/Python/S2S-download/projects/SST_oppdrett/',
    'S2SH_HR': '/nird/projects/NS9853K/DATA/S2S/MARS/hindcast/ECMWF/sfc/',
    'ERA5_HR': '/nird/projects/NS9853K/DATA/SFE/ERA_daily_nc/',
    'MPL_STYLE': '/nird/projects/NS9001K/sso102/Python/S2S-download/S2S/graphics/s2s.mplstyle'}
